### PR TITLE
kubectl: install useful plugins

### PR DESCRIPTION
**Pull request by frealmyr**
List of plugins available from krew:
https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md

This PR will install the following kubectl plugins:
- https://cert-manager.io/docs/usage/kubectl-plugin/
- https://github.com/rikatz/kubepug
- https://github.com/itaysk/kubectl-neat
- https://github.com/runoncloud/kubectl-np-viewer
- https://popeyecli.io/
- https://github.com/jordanwilson230/kubectl-plugins/tree/krew#kubectl-prompt
- https://github.com/robscott/kube-capacity
- https://github.com/Ladicle/kubectl-rolesum
- https://github.com/zegl/kube-score
- https://github.com/ahmetb/kubectl-tree

⚠️  Reviewers, please inspect each plugin _**before approving**_ for any oddities, or if you are unsure that we should add said plugin!

### CODE REVIEW

**Comment by jonasberdal** [comment]
> Caution: Kubectl plugins available via the Krew plugin index are not audited for security. You should install and run third-party plugins at your own risk, since they are arbitrary programs running on your machine.

**Comment by jonasberdal** [comment]
Trenger vi alle disse pluginene nå? Kanskje vi skal legge til plugins etterhvert som behovet kommer.

**Comment by jonasberdal** [comment]
Mye snask her da.

**Comment by frealmyr** [comment]
> > Caution: Kubectl plugins available via the Krew plugin index are not audited for security. You should install and run third-party plugins at your own risk, since they are arbitrary programs running on your machine.

Which is why i added the inspection request in the body. 🙉 

We practically add seperately binaries that extend kubectl, so we should inspect the repositories of the plugins.

**Comment by frealmyr** [comment]
Another way to use plugins, would be to figure how to use volumes to make plugin install persistent on clients.

**Comment by jonasberdal** [comment]
Based on number of stars and descriptions, all of these plugins seems fine. But to be completely sure we must review all the code and then check that the checksums matches. I don't think we have the capacity to do that for every update 🤔 We could also just accept the extra risk.

**Review by djfinnoy — APPROVED** [review]

**Comment by frealmyr** [comment]
@Starefossen what's your take on this? Should we live on the edge?

**Comment by frealmyr** [comment]
> Trenger vi alle disse pluginene nå? Kanskje vi skal legge til plugins etterhvert som behovet kommer.

Some of them would be nice to always have available, like `tree`, `neat` and so on.

Others like the static code analysis and popeye are only used when we are actively investigating for issues or improvements, so maybe we can leave those out and install them when needed. 🤔

**Comment by frealmyr** [comment]
We also have the `krew` package manager now, so if we fix the volume mount for plugins. Then plugin search and installation is low effort from our clients.

**Review by Starefossen — APPROVED** [review]
Looks awesome 🤘🏼

**Pull request merged**
